<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-OO3PNTG" ignored="0" tests="4" failures="2" timestamp="13 Jul 2021 11:33:45 GMT" time="0.069" errors="0">
  <testcase name="add1Test" time="0.013" classname="DataProviderExample"/>
  <testcase name="add1Test" time="0.003" classname="DataProviderExample">
    <failure type="java.lang.AssertionError" message="expected [20] but found [15]">
      <![CDATA[java.lang.AssertionError: expected [20] but found [15]
at DataProviderExample.add1Test(DataProviderExample.java:27)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- add1Test -->
  <testcase name="add1Test" time="0.001" classname="DataProviderExample"/>
  <testcase name="add1Test" time="0.003" classname="DataProviderExample">
    <failure type="java.lang.AssertionError" message="expected [50] but found [31]">
      <![CDATA[java.lang.AssertionError: expected [50] but found [31]
at DataProviderExample.add1Test(DataProviderExample.java:27)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- add1Test -->
</testsuite>
